---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/12 17:31
---


local M = {}

---获得属性，+- Attack / +- Health
---@param ExecutorID integer
---@param TriggeredID integer
---@param TargetID integer
---@param AttackParams table
---@param HealthParams table
---@param BattleManager AProjectJBattleManager
function M:GetAttribute(ExecutorID, TriggeredID, TargetID, AttackParams, HealthParams, BattleManager)
    --local GiveAttributeEvent = UE.FProjectJGameEventData();
    --if #AttackParams >= 1 then
    --    local AttackValue = AttackParams[1];
    --    local IsPermanentAttack = AttackParams[2] or false;
    --    GiveAttributeEvent.EventKVs:Add(AttackAttributeValueKey,tostring(AttackValue));
    --    if IsPermanentAttack then
    --        GiveAttributeEvent.EventKVs:Add(IsPermanentAttackKey,"");
    --    end
    --end
    --
    --if #HealthParams >= 1 then
    --    local HealthValue = HealthParams[1];
    --    local IsPermanentHealth = HealthParams[2] or false;
    --    GiveAttributeEvent.EventKVs:Add(HealthAttributeValueKey,tostring(HealthValue));
    --    if IsPermanentHealth then
    --        GiveAttributeEvent.EventKVs:Add(IsPermanentHealthKey,"");
    --    end
    --end
    --
    --GiveAttributeEvent.ExecutorID = ExecutorID;
    --GiveAttributeEvent.TriggeredID = TriggeredID;
    --GiveAttributeEvent.TargetID = TargetID;
    --
    --GiveAttributeEvent.EventTag.TagName = Game_Event_GetAttribute;
    --BattleManager:ExecuteEvent(GiveAttributeEvent);
end

---获得伤害
---@param ExecutorID integer
---@param TargetID integer
---@param Value integer
---@param BattleManager AProjectJBattleManager
function M:GetDamage(ExecutorID, TargetID, Value, BattleManager)
    local GiveDamageEvent = UE.FProjectJBattleEventData();
    GiveDamageEvent.ExecutorID = ExecutorID;
    GiveDamageEvent.TargetID = TargetID;
    GiveDamageEvent.EventKVs:Add(Battle_DamageValueKey, tostring(Value));
    GiveDamageEvent.EventTag.TagName = Battle_Event_GetDamage;
    BattleManager:ExecuteEvent(GiveDamageEvent);
end

---获得特性
---@param ExecutorID integer
---@param TargetID integer
---@param Feature string
---@param Round integer
---@param LayerCount integer
---@param BattleManager AProjectJBattleManager
function M:GetFeature(ExecutorID, TargetID, Feature, Round, LayerCount,BattleManager)
    local GetFeatureEvent = UE.FProjectJBattleEventData();
    GetFeatureEvent.ExecutorID = ExecutorID;
    GetFeatureEvent.TargetID = TargetID;
    GetFeatureEvent.EventKVs:Add(Battle_GetFeatureKey, Feature);
    GetFeatureEvent.EventKVs:Add(Battle_GetFeatureRoundKey, tostring(Round));
    GetFeatureEvent.EventKVs:Add(Battle_GetFeatureLayerCountKey, tostring(LayerCount));
    GetFeatureEvent.EventTag.TagName = Battle_Event_GetFeature;
    BattleManager:ExecuteEvent(GetFeatureEvent);
end

return M