---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-11
---

local M={}

_G.Montage_GameCard_NormalAttack_Montage = "/Game/Assets/Model/UECardAnimations/GameCard_NormalAttack_Montage.GameCard_NormalAttack_Montage"
_G.Montage_GameCard_OnHit_Montage = "/Game/Assets/Model/UECardAnimations/GameCard_OnHit_Montage.GameCard_OnHit_Montage"
_G.Effect_BP_Effect_Heal = "/Script/Engine.Blueprint"
_G.Effect_BP_Effect_Lighting = "/Script/Engine.Blueprint"

return M