---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-25
---

local M={}

_G.Test = "Test"
_G.Battle_DamageValueKey = "Battle_DamageValue"
_G.Battle_HealValueKey = "Battle_HealValue"
_G.Battle_GetFeatureKey = "Battle_GetFeature"
_G.Battle_GetFeatureRoundKey = "Battle_GetFeatureRound"
_G.Battle_GetFeatureLayerCountKey = "Battle_GetFeatureLayerCount"
_G.Program_Ani_NameKey = "Program_Ani_Name"
_G.Program_Ani_LocationKey = "Location"
_G.Program_Ani_Knock = "Program_Ani_Knock"
_G.GuanCha = "SpellGuanCha"
_G.YinBi = "SpellYinBi"
_G.TouXi = "SpellTouXi"
_G.TouQie = "SpellTouQie"
_G.Montage_GameCard_NormalAttack_Montage = "/Game/Assets/Model/UECardAnimations/GameCard_NormalAttack_Montage.GameCard_NormalAttack_Montage"
_G.Montage_GameCard_OnHit_Montage = "/Game/Assets/Model/UECardAnimations/GameCard_OnHit_Montage.GameCard_OnHit_Montage"
_G.Effect_Default = "Effect_Default"
_G.Effect_Heal = "Effect_Heal"
_G.Effect_Lightning = "Effect_Lightning"

return M