---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-13
---

local M={}

_G.Test = "Test"
_G.Debug_Buff = "Debug.Buff"
_G.Ability_ActionPoint0 = "Ability.ActionPoint0"
_G.Ability_ActionPoint1 = "Ability.ActionPoint1"
_G.Ability_ActionPoint2 = "Ability.ActionPoint2"
_G.Ability_ActionPoint3 = "Ability.ActionPoint3"
_G.Ability_ActionPoint4 = "Ability.ActionPoint4"
_G.Ability_ActionPoint5 = "Ability.ActionPoint5"
_G.SetByCaller_Attribute_Battle_Health = "SetByCaller.Attribute.Battle.Health"
_G.SetByCaller_Attribute_Battle_Attack = "SetByCaller.Attribute.Battle.Attack"
_G.SetByCaller_Attribute_Battle_Speed = "SetByCaller.Attribute.Battle.Speed"
_G.SetByCaller_Attribute_Battle_Armor = "SetByCaller.Attribute.Battle.Armor"
_G.SetByCaller_Attribute_Battle_Damage = "SetByCaller.Attribute.Battle.Damage"
_G.Feature_Loose_OneDamageEachTime = "Feature.Loose.OneDamageEachTime"
_G.Feature_None = "Feature.None"
_G.Feature_Stun = "Feature.Stun"
_G.Feature_Taunt = "Feature.Taunt"
_G.Feature_Poison = "Feature.Poison"
_G.Battle_Event_None = "Battle.Event.None"
_G.Battle_Event_RoundStart = "Battle.Event.RoundStart"
_G.Battle_Event_RoundEnd = "Battle.Event.RoundEnd"
_G.Battle_Event_BeforeAttack = "Battle.Event.BeforeAttack"
_G.Battle_Event_AttackHit = "Battle.Event.AttackHit"
_G.Battle_Event_AfterAttack = "Battle.Event.AfterAttack"
_G.Battle_Event_GetDamage = "Battle.Event.GetDamage"
_G.Battle_Event_GetHeal = "Battle.Event.GetHeal"
_G.Battle_Event_GetFeature = "Battle.Event.GetFeature"
_G.Battle_Event_Dead = "Battle.Event.Dead"

return M