---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-25
---

local M={}

_G.Level_CeShiGuanQia = "测试关卡"
_G.Level_ZhongXinGuangChang = "中心广场"
_G.Character_CeShiJueSe = "测试角色"
_G.Character_DaoZhu = "岛主"
_G.Character_CeShiYongZhuJue = "测试用主角"
_G.Landmark_JuShi = "巨石"
_G.Landmark_JinSuoDeFangJian = "紧锁的房间"
_G.Landmark_WeiShangSuoDeBaoXiang = "未上锁的宝箱"
_G.Utility_ShiTou = "石头"
_G.Utility_CeShiGuanQiaDeYaoShi = "测试关卡的钥匙"
_G.Weapon_QuanTou = "拳头"
_G.Weapon_LeiDianFaZhang = "雷电法杖"
_G.Weapon_ZhiLiaoFaZhang = "治疗法杖"
_G.Weapon_BuWenDingHuaHeWu = "不稳定化合物"
_G.Weapon_DuBiShou = "毒匕首"
_G.Armor_PoYiFu = "破衣服"
_G.Armor_ChaoFengYi = "嘲讽衣"
_G.Armor_KuiJia = "盔甲"
_G.Prop_YaoShi = "钥匙"

return M