---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-15
--- RowName：测试关卡
---

local M = {StartTickFrame = -1}

---[[[
--- 进入该关卡时
---@param ContextSystem UProjectJContextSystem
---@param EventSystem UProjectJEventSystem
---]]]
function M:EnterDungeon(ContextSystem, EventSystem)
    --- 播放剧情， 写入剧情描述
    local StoryRecord = UE.FProjectJStoryRecord();
    StoryRecord.Story:Add(
            NSLOCTEXT("Unlua", "Story_CeshiGuanQia_1", "进入房间，击杀目标角色，任务完成")
    );

    EventSystem.PostStoryRecord:Broadcast(StoryRecord);
end

return M