---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-11-19
--- RowName：岛主
---

local M = {StartTickFrame = -1}




---[[[
--- 每帧执行
---@param OwnerID integer
---@param Frame integer
---@return boolean
---]]]
function M:ExecuteTick(OwnerID, Frame)
    return false;
end


---[[[
--- 隐藏动画播放结束后执行
---@param OwnerID integer
---]]]
function M:ExecuteAfterHide(OwnerID)
end

return M