---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-25
--- RowName：隐蔽
---

local M = {SelfID = nil, StartTickFrame = nil, SelectedID = nil, SelectedCardType = nil}

---[[[
--- 返回可以使用的目标筛选器； 默认对所有角色、地标可用
--- @return FProjectJTargetFilter
---]]]
function M:GetTargetFilter()
    return DefaultPropTargetFilter;
end

---[[[
--- 返回执行时间(分钟)
--- @return integer
---]]]
function M:GetExecuteMinutes()
    return 5;
end

---[[[
--- 选择目标时执行
---]]]
function M:ExecuteSelectTarget()

end

---[[[
--- 每帧执行
---@param Frame integer
---]]]
function M:ExecuteTick(Frame)
end

---[[[
--- 执行完毕
---]]]
function M:ExecuteOver()
    self.RollResult = ExecHelper:Roll(SetByCaller_Attribute_Play_Observe);
end

---[[[
--- 隐藏动画播放结束后执行
---]]]
function M:ExecuteAfterHide()
    ExecHelper:ReSpawnSpell(self.SelfID);
    ExecHelper:OnSpellToCard(YinBi, self.SelectedID, self.RollResult);
end

return M