---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-23
--- RowName：石头
---

local M = {StartTickFrame = -1}

---[[[
--- 返回可以使用的目标筛选器； 默认对所有角色、地标可用
--- @return FProjectJTargetFilter
---]]]
function M:GetTargetFilter()
   return DefaultPropTargetFilter;
end

---[[[
--- 每帧执行
---@param OwnerID integer
---@param TargetID integer
---@param Frame integer
---@param ExecHelper UProjectJCardExecuteHelper
---@return boolean
---]]]
function M:ExecuteTick(OwnerID, TargetID,Frame, ExecHelper)
    return false;
end

---[[[
--- 隐藏动画播放结束后执行
---@param OwnerID integer
---@param ExecHelper UProjectJCardExecuteHelper
---]]]
function M:ExecuteAfterHide(OwnerID, ExecHelper)
end

return M