---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-22
--- RowName：未上锁的宝箱
---

local M = {StartTickFrame = -1}

---[[[
--- 每帧执行
---@param OwnerID integer
---@param Frame integer
---@return boolean
---]]]
function M:ExecuteTick(OwnerID, Frame)
    --- 简单表达5帧后执行完成
    if (Frame - self.StartTickFrame) == 5 then
       return true;
    end
    
    return false;
end

---[[[
--- 隐藏动画播放结束后执行
---@param OwnerID integer
---]]]
function M:ExecuteAfterHide(OwnerID)
    --- 销毁自己
    ExecHelper:DestroyCard(OwnerID);
    --- 创建一个钥匙卡牌
    ExecHelper:PopupUtility(Utility_CeShiGuanQiaDeYaoShi);
end

return M