---
--- Generated by Code, 不要修改函数和入参
--- Created by Lomo.
--- DateTime: 2024-12-22
--- RowName：未上锁的宝箱
---

local M = {SelfID = nil, StartTickFrame = nil}

---[[[
--- 每帧执行
---@param Frame integer
---]]]
function M:ExecuteTick(Frame)
    --- 简单表达5帧后执行完成
    if (Frame - self.StartTickFrame) == 5 then
       return true;
    end
    
    return false;
end

---[[[
--- 隐藏动画播放结束后执行
---]]]
function M:ExecuteAfterHide()
    --- 销毁自己
    ExecHelper:DestroyCard(OwnerID);
    --- 创建一个钥匙卡牌
    ExecHelper:PopupUtility(Utility_CeShiGuanQiaDeYaoShi);
end


---[[[
--- 返回执行时间(分钟)
--- @return integer
---]]]
function M:GetExecuteMinutes()
    return 15;
end


---[[[
--- 执行完毕
---]]]
function M:ExecuteOver()

end


---[[[
--- 收到了行为卡的执行结果
--- @param SpellTag string
--- @param RollResult integer
---]]]
function M:OnGetSpellResult(SpellTag, RollResult)
    ExecHelper:DefaultActionToSpell(SpellTag, self.SelfID);
end

return M